<?php
/**
 * Response
 *
 * PHP version 5
 *
 * @category Class
 * @package  APIHub\Client
 * @author   APIHub Codegen team
 * @link     https://github.com/apihub-api/apihub-codegen
 */

/**
 * FICO Score
 *
 * La API para FICO Score calcula el Score de la persona consultada.
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/apihub-api/apihub-codegen.git
 * APIHub Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the apihub code generator program.
 * https://github.com/apihub-api/apihub-codegen
 * Do not edit the class manually.
 */

namespace APIHub\Client\Model;

use \ArrayAccess;
use \APIHub\Client\ObjectSerializer;

class Response implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    protected static $apihubModelName = 'Response';

    protected static $apihubTypes = [
        'score' => 'int',
        'razones' => '\APIHub\Client\Model\Reason[]'
    ];

    protected static $apihubFormats = [
        'score' => 'int32',
        'razones' => null
    ];

    public static function apihubTypes()
    {
        return self::$apihubTypes;
    }

    public static function apihubFormats()
    {
        return self::$apihubFormats;
    }

    protected static $attributeMap = [
        'score' => 'score',
        'razones' => 'razones'
    ];

    protected static $setters = [
        'score' => 'setScore',
        'razones' => 'setRazones'
    ];

    protected static $getters = [
        'score' => 'getScore',
        'razones' => 'getRazones'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    public function getModelName()
    {
        return self::$apihubModelName;
    }

    

    

    protected $container = [];

    public function __construct(array $data = null)
    {
        $this->container['score'] = isset($data['score']) ? $data['score'] : null;
        $this->container['razones'] = isset($data['razones']) ? $data['razones'] : null;
    }

    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['score'] === null) {
            $invalidProperties[] = "'score' can't be null";
        }
        if ($this->container['razones'] === null) {
            $invalidProperties[] = "'razones' can't be null";
        }
        return $invalidProperties;
    }

    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    public function getScore()
    {
        return $this->container['score'];
    }

    public function setScore($score)
    {
        $this->container['score'] = $score;

        return $this;
    }

    public function getRazones()
    {
        return $this->container['razones'];
    }

    public function setRazones($razones)
    {
        $this->container['razones'] = $razones;

        return $this;
    }
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


