<?php
/**
 * ApiException
 * PHP version 5
 *
 * @category Class
 * @package  APIHub\Client
 * @author   APIHub Codegen team
 * @link     https://github.com/apihub-api/apihub-codegen
 */

/**
 * FICO Score
 *
 * La API para FICO Score calcula el Score de la persona consultada.
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/apihub-api/apihub-codegen.git
 * APIHub Codegen version: 2.4.2
 */

/**
 * NOTE: This class is auto generated by the apihub code generator program.
 * https://github.com/apihub-api/apihub-codegen
 * Do not edit the class manually.
 */

namespace APIHub\Client;

use \Exception;

class ApiException extends Exception
{

    protected $responseBody;

    protected $responseHeaders;

    protected $responseObject;

    public function __construct($message = "", $code = 0, $responseHeaders = [], $responseBody = null)
    {
        parent::__construct($message, $code);
        $this->responseHeaders = $responseHeaders;
        $this->responseBody = $responseBody;
    }

    public function getResponseHeaders()
    {
        return $this->responseHeaders;
    }

    public function getResponseBody()
    {
        return $this->responseBody;
    }

    public function setResponseObject($obj)
    {
        $this->responseObject = $obj;
    }

    public function getResponseObject()
    {
        return $this->responseObject;
    }
}
